---
title: "NSFPGRP_HostMutants_C86meliloti"
author: Sohini Guha,Gina Bledsoe,Liana T. Burghardt
date: "`r Sys.Date()`"
output: html_document
---

Analysis file for NSF Host Mutant C86 Ensifer meliloti select and resequence project. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load packages needed. Tidyverse include dplyer
require(tidyverse)
require(ggpubr)
require(ggplot2)
require(RColorBrewer)
knitr::opts_chunk$set(message = FALSE)
```

```{r merging all data sets, echo=TRUE}
# Import the text file of nodule data
data_HostMutants2021_nod_counts <- read.table("../data/data_HostMutants2021_nod_counts.txt",sep = "\t",header=TRUE)
# Import the genotype information data
genotype_name <- read.table("../data/genotype_name.txt",sep = "\t",header=TRUE)

#removing rows marked "853","838","888","889","890"
genotype_name<-subset(genotype_name,genotype_id!="853")
genotype_name<-subset(genotype_name,genotype_id!="838")
genotype_name<-subset(genotype_name,genotype_id!="888")
genotype_name<-subset(genotype_name,genotype_id!="889")
genotype_name<-subset(genotype_name,genotype_id!="890")
#import the text file with the CFU data
data_nsfpgrp_hostmutants_C86meliloti <- read.table("../data/data_nsfpgrp_hostmutants_C86meliloti.txt",sep = "\t",header=TRUE)
#merge  data_HostMutants2021_nod_counts.txt,data_nsfpgrp_hostmutants_C86meliloti.txt, by 'sample_id","genotype_id" and "rep"
all.data <-full_join (data_HostMutants2021_nod_counts,data_nsfpgrp_hostmutants_C86meliloti,by=c("sample_id","genotype_id","rep"))
# merge the newly created table with the "genotype_name"
all.data <-full_join (all.data,genotype_name,by = "genotype_id")
#removing columns marked "batch","start","end","num_alive_apr15"
all.data<-subset (all.data, select=-c(X,batch,start,end,num_alive_apr15))
#adding above_biomass_g/plant,below_biomass_g/plant,ratio and total_biomass
all.data<-all.data%>% mutate(above_biomass_perplant=above_biomass_g/num_plants,below_biomass_perplant=below_biomass_g/num_plants,ratio=below_biomass_perplant/above_biomass_perplant,total_biomass=above_biomass_perplant+below_biomass_perplant)
#adding nodules/plant
all.data<-all.data%>% mutate(nodules_perplant=Count/num_plants_picked_nods)
#adding cfu per plant - divide by 4ml (this is the amount added to nodules to homogenize) then divide by number of plants picked nodules from to get cfu/ml to cfu/plant;cfupernodule
table(is.na(all.data$cfu_ml)) # 27 NA's (why are you counting the number of NAs in the cfu_ml col? )
table(all.data$cfu_ml==0) # No Zeros. 
#There are two reasons it could be a zero either there were no nodules picked and thus no rhizobia or there was a problem with the estimation of cfu. In the first case the 0 is meaningful but from an analysis standpoint we probably still want to ommit them becuase the model won't behave well.

all.data<-all.data%>% mutate(CFUperplant=cfu_ml/num_plants_picked_nods/4, CFUpernodule=CFUperplant/nodules_perplant)
#converting CFUperplant and CFUpernodule to log(CFUperplant),log(CFUpernodule)
all.data<-all.data%>% mutate(log_CFUperplant=log10(CFUperplant),log_CFUpernodule=log10(CFUpernodule))
#adding total_nodulated area_perplant and Nodulesize_perplant
all.data<-all.data%>% mutate(total_nodulated_area_perplant=total_area/num_plants_picked_nods,Nodulesizeperplant=total_nodulated_area_perplant/nodules_perplant)
#adding weight pernodule and totalnodule weight per plant
all.data<-all.data%>% mutate(Nodule_weight_perplant=nodule_weight_g/num_plants_picked_nods,Weight_pernodule=Nodule_weight_perplant/nodules_perplant)
#replacing  'inf' with 'NA'(the sample 846A needs to be removed)
all.data[is.na(all.data) | all.data == "Inf"] <- NA
write.table (all.data,file="../data/Traits_MedicagoMutants.txt",sep = "\t",row.names = FALSE)
```

```{r Importing Data and polishing the table, echo=TRUE}
# Importing the data
Traits_MedicagoMutants<- read.table("../data/Traits_MedicagoMutants.txt",sep = "\t",header=TRUE)
#convert the genotype_id into integer
Traits_MedicagoMutants$genotype_id = as.integer(Traits_MedicagoMutants$genotype_id)
#Select for only the A17 background
all.data.A17 <- Traits_MedicagoMutants %>% filter(background=="A17")
# Removing two genotypes that did not survive/form nodules.
all.data.A17 <- all.data.A17 %>% filter(genotype_id!="853")
all.data.A17 <- all.data.A17 %>% filter(genotype_id!="838")
#remove 847F
all.data.A17<-all.data.A17%>%filter(sample_id!= "847F")
#remove 833A
all.data.A17<-all.data.A17%>%filter(sample_id!= "833A")
# Remove 833B
all.data.A17<-all.data.A17%>%filter(sample_id!="833B")
#Turning all.data.A17$name  into a factor.
all.data.A17$name<-factor(all.data.A17$name)
#Turning all.data.A17$Type into a factor.
all.data.A17$type<-factor(all.data.A17$type, levels = c("WT","Early","Late","AON"))
#Changing the order of the genotypes
all.data.A17$name<-factor(all.data.A17$name,levels=c("A17", "dmi1-2","dmi2-3","dmi3-1","hcl","ipd3","latd", "nad1", "dnf1", "dnf2","dnf3", "dnf4","dnf6","dnf7", "dnf1/dnf2", "dnf5/dnf2", "rdn1", "sunn1","sunn4"))
```

```{r Boxplots, echo=TRUE}
### For emulating ggplot colors ###
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
mypal<-gg_color_hue(6)

#color palette for standard plots - colorblind friendly
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442")


l = length(seq(-7.9, 8, 0.1))
pal = colorRampPalette(c('#2166AC', '#F7F7F7', '#B2182B'))(l)

#Allows visualization of a color Palette
#require(scales)
#show_col(cbPalette)

# Define a color and shape scheme for the whole manuscript
#mycols<-data.frame(type=c("AON","Early","Late","WT"), cols=cbPalette)
#mycols$type <- factor(mycols$type, ordered=TRUE)

all.data.A17$name<-factor(all.data.A17$name,levels = rev(levels(all.data.A17$name)))

#Boxplot depicting nodulation per plant 
nod_cnt <-ggplot(all.data.A17,aes(x=name, y=nodules_perplant,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="Nodules per plant") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
nod_cnt 
```

```{r}
#Boxplot depicting average nodule size per plant
nod_size<-ggplot(all.data.A17,aes(x=reorder(name,type), y=Nodulesizeperplant,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="Average NoduleSize per plant") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
nod_size
#Boxplot depicting total nodulated area per plant
tot_nod_area<-ggplot(all.data.A17,aes(x=reorder(name,type), y=total_nodulated_area_perplant,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="Total Nodulated Area per plant") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
tot_nod_area

#Boxplot depicting CFU per plant
cfu_per_plant<-ggplot(all.data.A17,aes(x=reorder(name,type), y=log_CFUperplant,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="log(CFU per plant)") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
cfu_per_plant
#Boxplot depicting CFU per nodule
cfu_per_nodule<-ggplot(all.data.A17,aes(x=reorder(name,type), y=log_CFUpernodule,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="log(CFU per nodule") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
cfu_per_nodule
#Boxplot depicting total biomass
total_biomass<-ggplot(all.data.A17,aes(x=reorder(name,type), y=total_biomass,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="Total Biomass(mg)") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
total_biomass
#Boxplot depicting Nodule_weight_perplant
Nodule_weight_perplant<-ggplot(all.data.A17,aes(x=reorder(name,type), y=Nodule_weight_perplant,fill=type)) + geom_boxplot(outlier.shape=NA)+geom_jitter()+coord_flip()+scale_color_manual(values=cbPalette)+labs(x="Plant Host",y="Nodule weight perplant")+theme_classic()+theme(legend.position="top",text = element_text(size=18))
Nodule_weight_perplant
#Boxplot depicting ratio of above and below ground biomass
biomass_ratio<-ggplot(all.data.A17,aes(x=reorder(name,type), y=ratio,fill=type)) + 
        geom_boxplot(outlier.shape=NA) +
        geom_jitter() +
        coord_flip() +
        scale_color_manual(values=cbPalette)  +
        labs(x="Plant Host",y="Belowground:Aboveground") +
        theme_classic() + theme(legend.position="top", text = element_text(size=18))
biomass_ratio


```

```{r Linear model code Nod Num , echo=TRUE}
# Run a model with name and replicate as predictors
NodNum.G <- lm(nodules_perplant ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors
NodNum.T<-lm(nodules_perplant ~ type + rep, data = all.data.A17)
#Examine the summaries
summary(NodNum.G)
summary(NodNum.T)
#Examine the Analysis of Variance tables
a.G<-anova(NodNum.G)
a.G
a.T<-anova(NodNum.T)
a.T


```


```{r Write Function to extract Statistical summary of coefficients, echo=TRUE}
extract.summary<-function(trait) {
#Dropping rows with NA
#all.data.A17 <- all.data.A17 [complete.cases(all.data.A17), ] # This needs to be made specific to the trait! See below
all.data.A17<-all.data.A17[!is.na(all.data.A17[,trait]),] 
# Run a model with name and replicate as predictors
trait.G <- lm(all.data.A17[,trait] ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors (why the ,?)
trait.T<-lm(all.data.A17[,trait] ~ type + rep, data = all.data.A17)
# Extract the coefficients
  coefs.G <- summary(trait.G)$coefficients
  coefs.T<-summary(trait.T)$coefficients
#Convert the coefficients into a  dataframe
  coefs.G<-as.data.frame(coefs.G)
  coefs.T<-as.data.frame(coefs.T)
# Create a data frame with the coefficients, trait, and p-value
myresults2<-data.frame(Response=c(paste(trait)),Coefficient=coefs.G$'Estimate',Pvalue=coefs.G$'Pr(>|t|)')
#create a dataframe with the predictors
myresults1<-data.frame(Genotype=c("(Intercept)","dmi1-2","dmi2-3","dmi3-1","hcl","ipd3","latd","nad1","dnf1","dnf2","dnf3","dnf4","dnf6","dnf7","dnf1/dnf2", "dnf5/dnf2","rdn1","sunn1","sunn4","repB","repC","repD","repE"))

length(myresults2)<-length(myresults1)
#Combine
myresults<-cbind(myresults1,myresults2)
# Return the data frame
  return(myresults)
}                  
                      

```

```{r Write Function to compile and summarize results each Phenotype, echo=TRUE}
TRAIT.summary<-rbind(extract.summary("nodules_perplant"),extract.summary("average_size"),extract.summary("total_area"),extract.summary("total_nodulated_area_perplant"),extract.summary("total_biomass"),extract.summary("ratio"),extract.summary("log_CFUpernodule"),extract.summary("log_CFUperplant"))
write.table (TRAIT.summary,file="../tables/Trait-Summary.txt",sep = "\t",row.names = FALSE)

```

```{r Write Function to run anova and summarize results each Phenotype, echo=TRUE}

extract.anova<- function(trait) {
#Dropping rows with NA
#all.data.A17 <- all.data.A17 [complete.cases(all.data.A17), ] # This needs to be made specific to the trait! See below
all.data.A17<-all.data.A17[!is.na(all.data.A17[,trait]),] 

# Run a model with name and replicate as predictors
NodNum.G <- lm(all.data.A17[,trait] ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors (why the ,?)
NodNum.T<-lm(all.data.A17[,trait] ~ type + rep, data = all.data.A17)
#Examine the Analysis of Variance tables and save output
a.G<-anova(NodNum.G)
a.T<-anova(NodNum.T)

#Compile results into a dataframe
myresults<-data.frame(Response=c(paste(trait)),Predictor=c("Genotype","Replicate","Residual","Type","Replicate","Residual"),Sum.Sq=c(a.G$"Sum Sq",a.T$"Sum Sq"),PctExp=c(a.G$"Sum Sq"/sum(a.G$"Sum Sq")*100,a.T$"Sum Sq"/sum(a.T$"Sum Sq")*100),Df=c(a.G$"Df",a.T$"Df"),Fval=c(a.G$"F value",a.T$"F value"), Pval=c(a.G$"Pr(>F)",a.T$"Pr(>F)"),R.adj=c(summary(NodNum.G)$adj.r.squared,"NA","NA",summary(NodNum.T)$adj.r.squared,"NA","NA"))

return(myresults)

}

```


```{r Compile across Phenotypes, echo=TRUE}
ANOVA.Trait.Summary<-rbind(extract.anova("nodules_perplant"),
extract.anova("average_size"),
extract.anova("total_area"),extract.anova("total_nodulated_area_perplant"),extract.anova("total_biomass"),extract.anova("ratio"),extract.anova("Nodule_weight_perplant"),extract.anova("log_CFUpernodule"),extract.anova("log_CFUperplant"))

write.table (ANOVA.Trait.Summary,file="../tables/ANOVA-Trait-Summary.txt",sep = "\t",row.names = FALSE)

```

```{r Writing a function for the box-plots, echo=TRUE}
#Nodule_weight_perplant<-ggplot(all.data.A17,aes(x=reorder(name,type), y=Nodule_weight_perplant,fill=type)) + geom_boxplot(outlier.shape=NA)+geom_jitter()+coord_flip()+scale_color_manual(values=cbPalette)+labs(x="Plant Host",y="Nodule weight perplant")+theme_classic()+theme(legend.position="top",text = element_text(size=18))


#Nodule_weight_perplant





#boxplot.trait<- function(trait) {

# Run a model with name and replicate as predictors
#NodNum.G <- lm(all.data.A17[,trait] ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors
#NodNum.T<-lm(all.data.A17[,trait] ~ type + rep, data = all.data.A17)

#Examine the Analysis of Variance tables and save output
#a.G<-anova(NodNum.G)
#a.T<-anova(NodNum.T)

#Compile results into a dataframe
#myresults<-data.frame(Response=c(paste(trait)),Predictor=c("Genotype","Replicate","Residual","Type","Replicate","Residual"),Sum.Sq=c(a.G$"Sum Sq",a.T$"Sum Sq"),PctExp=c(p/sum(p)*100,q/sum(q)*100),Df=c(a.G$"Df",a.T$"Df"),Fval=c(a.G$"F value",a.T$"F value"), Pval=c(a.G$"Pr(>F)",a.T$"Pr(>F)"),R.adj=c(summary(NodNum.G)$adj.r.squared,"NA","NA",summary(NodNum.T)$adj.r.squared,"NA","NA"))

#return(myresults)


```


```{r Running a Linear Model for nodule size, echo=TRUE}
# Run a model with name and replicate as predictors
NodSize.G<-lm(Nodulesizeperplant ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors
NodSize.T<-lm(Nodulesizeperplant ~type+rep,data=all.data.A17)
#Examine the summaries
b<-summary(NodSize.G)
summary(NodSize.T)
#Examine the Analysis of Variance tables
p<-anova(NodNum.G)
p
q<-anova(NodNum.T)
q
# percentage of variance explained
p<-p$"Sum Sq"
print(cbind(PctExp=p/sum(p)*100))
q<-q$"Sum.Sq"
print(cbind(PctExp=q/sum(q)*100))
```



```{r Running a Linear Model for total nodulated area per plant, echo=TRUE}
# Run a model with name and replicate as predictors
TotNodArea.G<-lm(total_nodulated_area_perplant ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors
TotNodArea.T<-lm(total_nodulated_area_perplant ~type+rep,data=all.data.A17)
#Examine the summaries
summary(TotNodArea.G)
summary(TotNodArea.T)
#Examine the Analysis of Variance tables
p<-anova(TotNodArea.G)
p
q<-anova(TotNodArea.T)
q
# percentage of variance explained
p<-p$"Sum Sq"
print(cbind(PctExp=p/sum(p)*100))
q<-q$"Sum.Sq"
print(cbind(PctExp=q/sum(q)*100))
```

```{r Running a Linear Model for CFU per plant, echo=TRUE}
# Run a model with name and replicate as predictors
CFUperplant.G<-lm(CFUperplant ~ name + rep, data = all.data.A17)
# Run a model with type and replicate as predictors
CFUperplant.T<-lm(CFUperplant ~ type + rep, data = all.data.A17)
#Examine the summaries
summary(CFUperplant.G)
summary(CFUperplant.T)
#Examine the Analysis of Variance tables
p<-anova(CFUperplant.G)
p
q<-anova(CFUperplant.T)
q
# percentage of variance explained
p<-p$"Sum Sq"
print(cbind(PctExp=p/sum(p)*100))
q<-q$"Sum.Sq"
print(cbind(PctExp=q/sum(q)*100))
```

```{r Running a Linear Model for CFU per nodule, echo=TRUE}
# Run a model with name and replicate as predictors
pernodule.G<-lm(CFUpernodule ~ name + rep,data = all.data.A17)
# Run a model with type and replicate as predictors
pernodule.T<-lm(CFUpernodule ~ type + rep,data = all.data.A17)
#Examine the summaries
summary(pernodule.G)
summary(pernodule.T)
#Examine the Analysis of Variance tables
p<-anova(pernodule.G)
p
q<-anova(pernodule.T)
q
# percentage of variance explained
p<-p$"Sum Sq"
print(cbind(PctExp=p/sum(p)*100))
q<-q$"Sum.Sq"
print(cbind(PctExp=q/sum(q)*100))
```

```{r Running a Linear Model for ratio of above ground and below ground biomass, echo=TRUE}
# Run a model with name and replicate as predictors
ratio.G<-lm(ratio ~ name + rep,data = all.data.A17)
# Run a model with type and replicate as predictors
ratio.T<-lm(ratio ~ type + rep,data = all.data.A17)
#Examine the summaries
summary(ratio.G)
summary(ratio.T)
             
#Examine the Analysis of Variance tables
p<-anova(ratio.G)
p
q<-anova(ratio.T)
q
# percentage of variance explained
p<-p$"Sum Sq"
print(cbind(PctExp=p/sum(p)*100))
q<-q$"Sum.Sq"
print(cbind(PctExp=q/sum(q)*100))
```
#
```{r Creating the tables for the manuscript, echo=TRUE}
#extracting adjusted R-squared values across traits
mod_summary_NodNum.G<-summary(NodNum.G)

mod_summary_NodNum.T<-summary(NodNum.T)


mod_summary_TotNodArea.G<-summary(TotNodArea.G)
mod_summary_TotNodArea.T<-summary(TotNodArea.T)
mod_summary_CFUperplant.G<-summary(CFUperplant.G)
mod_summary_CFUperplant.T<-summary(CFUperplant.T)
mod_summary_NodSize.G<-summary(NodSize.G)
mod_summary_NodSize.T<-summary(NodSize.T)
mod_summary_ratio.G<-summary(ratio.G)
mod_summary_ratio.T<-summary(ratio.T)
mod_summary_pernodule.G<-summary(pernodule.G)
mod_summary_pernodule.T<-summary(pernodule.T)

a<-mod_summary_NodNum.G$adj.r.squared 
b<-mod_summary_NodNum.T$adj.r.squared 
c<-mod_summary_TotNodArea.G$adj.r.squared 
d<-mod_summary_TotNodArea.T$adj.r.squared 
e<-mod_summary_NodSize.G$adj.r.squared 
f<-mod_summary_NodSize.T$adj.r.squared 
g<-mod_summary_CFUperplant.G$adj.r.squared 
h<-mod_summary_CFUperplant.T$adj.r.squared 
i<-mod_summary_pernodule.G$adj.r.squared 
j<-mod_summary_pernodule.T$adj.r.squared 
k<-mod_summary_ratio.G$adj.r.squared 
l<-mod_summary_ratio.T$adj.r.squared 

df<-data.frame(Traits=c('Nodule Number','Total Nodulated Area','Size per Nodule','CFUperplant','CFUpernodule','Biomass Ratio'),Type=c(b,d,f,h,j,l),
               Genotype=c(a,c,e,g,i,k))
#create the table
tab1 <- table(df$Traits,df$Type,df$Genotype)
tab1
#write the table
write.table (tab1,file="adj.r.squared values across traits.txt",sep = "\t",row.names =FALSE)
```
