---
title: "Mutations in legume genes that influence symbiosis create a complex selective landscape for rhizobial symbionts"
author:  Sohini Guha, Regina B. Bledsoe, Jeremy Sutherland, Brendan Epstein, Gwendolyn M. Fry, Vikram Venugopal, Siva Sankari, Alejandra Gil Polo1, Garrett Levin, Barney Geddes, Nevin D. Young, Peter Tiffin, and Liana T. Burghardt
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages needed. Tidyverse include dplyer
require(tidyverse)
require(ggpubr)
require(ggplot2)
require(RColorBrewer)
require(gplots)
require(vegan)
require(CMplot)
knitr::opts_chunk$set(message = FALSE)
```

```{r setup,Import the data include=FALSE}
##Importing the GWAS files

#psymb
merged_psyma_ipd3.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_ipd3.tsv", header=TRUE)
merged_psyma_latd.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_latd.tsv",header=TRUE)
merged_psyma_hcl.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_hcl.tsv",header=TRUE)
merged_psyma_dnf1.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1.tsv",header=TRUE)
merged_psyma_dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf2.tsv",header=TRUE)
merged_psyma_dnf3.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf3.tsv",header=TRUE)
merged_psyma_dnf4.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf4.tsv",header=TRUE)
merged_psyma_dnf6.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf6.tsv",header=TRUE)
merged_psyma_dnf7.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf7.tsv",header=TRUE)
merged_psyma_dnf1dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1dnf2.tsv",header=TRUE)
merged_psyma_dnf5dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf5dnf2.tsv",header=TRUE)
merged_psyma_nad1.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_nad1.tsv",header=TRUE)
merged_psyma_rdn1.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_rdn1.tsv",header=TRUE)
merged_psyma_sunn1.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn1.tsv",header=TRUE)
merged_psyma_sunn4.change <- read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn4.tsv",header=TRUE)
merged_psyma_A17<-read.delim("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_A17.tsv",header=TRUE)

#psymb
merged_psymb_ipd3.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_ipd3.tsv", header=TRUE)
merged_psymb_latd.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_latd.tsv",header=TRUE)
merged_psymb_hcl.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_hcl.tsv",header=TRUE)
merged_psymb_dnf1.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1.tsv",header=TRUE)
merged_psymb_dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf2.tsv",header=TRUE)
merged_psymb_dnf3.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf3.tsv",header=TRUE)
merged_psymb_dnf4.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf4.tsv",header=TRUE)
merged_psymb_dnf6.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf6.tsv",header=TRUE)
merged_psymb_dnf7.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf7.tsv",header=TRUE)
merged_psymb_dnf1dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1dnf2.tsv",header=TRUE)
merged_psymb_dnf5dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf5dnf2.tsv",header=TRUE)
merged_psymb_nad1.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_nad1.tsv",header=TRUE)
merged_psymb_rdn1.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_rdn1.tsv",header=TRUE)
merged_psymb_sunn1.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn1.tsv",header=TRUE)
merged_psymb_sunn4.change <- read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn4.tsv",header=TRUE)
merged_psymb_A17<-read.delim("../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_A17.tsv",header=TRUE)

#chromosome 
merged_chr_ipd3.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_ipd3.tsv", header=TRUE)
merged_chr_latd.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_latd.tsv",header=TRUE)
merged_chr_hcl.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_hcl.tsv",header=TRUE)
merged_chr_dnf1.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1.tsv",header=TRUE)
merged_chr_dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf2.tsv",header=TRUE)
merged_chr_dnf3.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf3.tsv",header=FALSE)
merged_chr_dnf4.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf4.tsv",header=TRUE)
merged_chr_dnf6.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf6.tsv",header=TRUE)
merged_chr_dnf7.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf7.tsv",header=TRUE)
merged_chr_dnf1dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1dnf2.tsv",header=TRUE)
merged_chr_dnf5dnf2.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf5dnf2.tsv",header=TRUE)
merged_chr_nad1.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_nad1.tsv",header=TRUE)
merged_chr_rdn1.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_rdn1.tsv",header=TRUE)
merged_chr_sunn1.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn1.tsv",header=TRUE)
merged_chr_sunn4.change <- read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn4.tsv",header=TRUE)
merged_chr_A17<-read.delim("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_A17.tsv",header=TRUE)



```

```{r Code for creating the tables for the top5 candidates: TableS6 and Table2, echo=FALSE}
# List of file paths

 file_paths <- c("../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_ipd3.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_latd.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_hcl.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf3.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf4.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf6.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf7.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf5dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_nad1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_rdn1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn4.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_A17.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_ipd3.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_latd.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_hcl.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf3.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf4.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf6.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf7.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf5dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_nad1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_rdn1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn4.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_A17.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_ipd3.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_latd.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_hcl.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf2.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf3.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf4.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf6.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf7.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1dnf2.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf5dnf2.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_nad1.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_rdn1.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn1.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn4.tsv","../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_A17.tsv")  
# List to store data frames
data_list <- list()

read_and_store_data <- function(file_paths) {
  data <- read.delim(file_paths, header = TRUE)
  return(data)
}

# Read data frames and store in the list
data_list <- lapply(file_paths, read_and_store_data)
#top5_candidates

# Use lapply to apply the function to each data frame
#all_top_candidates_subsets <- lapply(data_list, get_top_candidates_subset_and_combine)
# Combine all subsets into a single data frame
#combined_data <- do.call(rbind, all_top_candidates_subsets)
#seperate the 'chr' col
#combined_top10_candidates_data<-combined_data%>% separate(chr,c('Organism','Replicon'))
#Table for Fig S6,S7

#select the top5 for fig6, supplement annotated heatmap and the crossranked tables
#top5_candidates<-subset(combined_top10_candidates_data,pr>=1 & pr<=5)
get_top_candidates_pr <- function(df) {
  df %>%
    filter(pr >= 1 & pr <= 5) %>%        # top 5 per trait
    distinct(ld_snps, .keep_all = TRUE) # remove duplicate SNPs
}

# Function to get top 5 candidates for Table 3 based on PRS + significance
get_top_candidates_prs <- function(df) {
  df %>%
    filter(prs >= 1 & prs <= 5) %>%      # top 5 cross-ranked
    filter(p_lrt <= 1e-5) %>%            # significant SNPs
    distinct(ld_snps, .keep_all = TRUE)  # remove duplicate SNPs
}

# Apply to your list of data frames
top_candidates_list_pr <- lapply(data_list, get_top_candidates_pr)
top_candidates_list_prs <- lapply(data_list, get_top_candidates_prs)

# Combine all traits
combined_top5 <- bind_rows(top_candidates_list_pr)
combined_top5_prs <- bind_rows(top_candidates_list_prs)
#TableS7
write.table(combined_top5,file="../Tables/strainfitness/top5candidates.tsv",sep = "\t",row.names = FALSE) 



write.table(combined_top5_prs,file="../Tables/strainfitness/top5candidates_prs.tsv",sep = "\t",row.names = FALSE)



```


```{r Code for manhattanplots for paper, echo=FALSE}

library(dplyr)
library(tidyr)

data_list_named <- Map(function(df, file) {
    df <- df %>%
        mutate(
            Chromosome = sapply(strsplit(chr, "-"), `[`, 2),  # extract part after '-'
            Position = ldg                                      # rename ldg to Position
        )
     
     df$Trait <- gsub(".*_trait_|\\.tsv$", "", basename(file))  # extract trait from filename
    return(df)
 }, data_list, file_paths)


 combined_gwas <- bind_rows(data_list_named)

# Now select and pivot
gwas_wide <- combined_gwas %>%
    dplyr::select(ldg, Chromosome, ps, Trait, p_lrt) %>%  # use actual column names
   distinct() %>% pivot_wider(
         names_from = Trait,
        values_from = p_lrt,
    )
 # Optional: rename ldg to LD_group
gwas_wide <- gwas_wide %>% rename(SNP = ldg, Position=ps)
desired_order <- c("Chromosome","SNP", "Position",
                   "A17", "dnf1", "dnf1dnf2", "dnf2", "dnf3", "dnf4",
                   "dnf5dnf2", "dnf6", "dnf7",
                   "hcl", "ipd3", "latd", "nad1", "rdn1", "sunn1", "sunn4")

gwas_wide <- gwas_wide[, desired_order]
gwas_wide$Chromosome <- factor(gwas_wide$Chromosome,
                               levels = c("chr", "pSymA", "pSymB"))

# (Optional) Check to confirm
levels(gwas_wide$Chromosome)

 # Check result
head(gwas_wide)
colnames(gwas_wide)
figures <- "/Users/sohiniguha/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/Sohini_Liana/GitHub/HostMutants2021_C86meliloti/strainfitness/figures"
# -----------------------------
# 0️⃣ Define colors for traits
colors_16 <- c("#0000ff", "#000000", "#5C5A5A", "#feb300", "#00aeae", "#ffff00", "#F5E4E4", "#ff4600", 
                "#53a1f0", "#e9c6ac", "#9d22f3", "#3d389a", "#95ef57", "#f311c1", "#0a82f0", "#cd93aa") 

# -----------------------------
# 1️⃣ Extract trait names from first row (columns 5:20)
trait_names <- colnames(gwas_wide)[4:19]

# -----------------------------
# 2️⃣ Remove first row (only contains trait names)
data_clean <- gwas_wide[-1, ]

# -----------------------------
# 3️⃣ Convert trait columns to numeric
data_clean[, 4:19] <- lapply(data_clean[, 4:19], function(x) as.numeric(as.character(x)))

# Optional: check for NAs
if(any(is.na(data_clean[, 4:19]))) {
  warning("Some trait columns contain NA values after conversion.")
}

# -----------------------------
# 4️⃣ Assign trait names as column names
colnames(data_clean)[4:19] <- trait_names

# -----------------------------
# 5️⃣ Ensure Position is numeric
data_clean$Position <- as.numeric(as.character(data_clean$Position))

# -----------------------------
# 6️⃣ Map Chromosome based on SNP names
data_clean$Chromosome <- ifelse(
  grepl("chr", data_clean$SNP, ignore.case = TRUE), "chr",
  ifelse(grepl("psyma", data_clean$SNP, ignore.case = TRUE), "pSymA",
         ifelse(grepl("psymb", data_clean$SNP, ignore.case = TRUE), "pSymB", NA))
)

# -----------------------------
# 7️⃣ Build cmdata for CMplot
cmdata <- data_clean[, c("SNP", "Chromosome", "Position", trait_names)]
cmdata$Chromosome <- factor(cmdata$Chromosome,
                               levels = c("chr", "pSymA", "pSymB"))
cmdata <- cmdata[order(cmdata$Chromosome, cmdata$Position), ]
# -----------------------------
# 8️⃣ Plot with CMplot
CMplot(cmdata,
       plot.type="m",
       col="grey",
       multraits=TRUE,
       threshold=1e-5,
       threshold.lty=2,
       threshold.lwd=1.5,
       threshold.col="black",
       amplify=TRUE,
       chr.den.col=NULL,
       signal.col=colors_16,
       signal.cex=1,
       file="jpg",
       file.name="Strainfitness_manhattanplot",
       dpi=300,
       file.output=TRUE,
       verbose=TRUE,
       points.alpha=225,  # integer 0-255
       legend.ncol=3,
       legend.pos="middle")


##Q-Qplot 
CMplot(cmdata,
       plot.type="q",
       col=colors_16,
       multraits=TRUE,
       conf.int=FALSE,
       box=FALSE,
       axis.cex=1,
       file="jpg",
       file.name="Strainfitness_output_file_qq",  # saves as qq.jpg
       dpi=300,
       file.output=TRUE,
       verbose=TRUE,
       ylim=c(0,12),
       width=7,
       height=7)

```

```{r Code for creating the cross-ranked candidates: TableS7, echo=FALSE}

merge_GWAS_data <- function(gene){
    # Construct file paths based on gene  name
    file_paths <- list(
  A17=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_A17.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_A17.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_A17.tsv"),
  hcl=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_hcl.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_hcl.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_hcl.tsv"),
  ipd3=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_ipd3.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_ipd3.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_ipd3.tsv"),
  nad1=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_nad1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_nad1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_nad1.tsv"),
  latd=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_latd.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_latd.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_latd.tsv"),
  dnf1=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1.tsv"),
  dnf2=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf2.tsv"),
dnf3=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf3.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf3.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf3.tsv"),
dnf4=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf4.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf4.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf4.tsv"),
  dnf6=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf6.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf6.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf6.tsv"),
  dnf7=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf7.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf7.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf7.tsv"),
  dnf1dnf2=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf1dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf1dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf1dnf2.tsv"),
dnf5dnf2=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_dnf5dnf2.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_dnf5dnf2.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_dnf5dnf2.tsv"),
rdn1=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_rdn1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_rdn1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_rdn1.tsv"),
sunn1=c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn1.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn1.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn1.tsv"),
sunn4= c("../data/GWAS_data/annotation1/merged_chr_subset_LD_ulmm_trait_sunn4.tsv","../data/GWAS_data/annotation1/merged_psyma_subset_LD_ulmm_trait_sunn4.tsv","../data/GWAS_data/annotation1/merged_psymb_subset_LD_ulmm_trait_sunn4.tsv")
        
    )
    
    # Check if gene argument is valid
    if (!(gene %in% c("A17","hcl","ipd3","latd","nad1","dnf1","dnf2","dnf3","dnf4","dnf6","dnf7","dnf1dnf2","dnf5dnf2","rdn1","sunn1","sunn4"))) {
        stop("Gene argument must be one of: A17,hcl,ipd3,latd,nad1,dnf1,dnf2,dnf3,dnf4,dnf6,dnf7,dnf1dnf2,dnf5dnf2,rdn1,sunn1,sunn4")
    }
    
    # Read the corresponding files for the given gene
    data <- lapply(file_paths[[gene]], read.delim, header = TRUE)
    
    # Merge the data
    merged_data <- do.call(rbind, data)
    
    return(merged_data)
    
}    



merged_A17 <- merge_GWAS_data("A17")
merged_hcl<-merge_GWAS_data("hcl")
merged_ipd3<-merge_GWAS_data("ipd3")
merged_latd<-merge_GWAS_data("latd")
merged_nad1<-merge_GWAS_data("nad1")
merged_dnf1<-merge_GWAS_data("dnf1")
merged_dnf2<-merge_GWAS_data("dnf2")
merged_dnf3<-merge_GWAS_data("dnf3")
merged_dnf4<-merge_GWAS_data("dnf4")
merged_dnf6<-merge_GWAS_data("dnf6")
merged_dnf7<-merge_GWAS_data("dnf7")
merged_dnf1dnf2<-merge_GWAS_data("dnf1dnf2")
merged_dnf5dnf2<-merge_GWAS_data("dnf5dnf2")
merged_rdn1<-merge_GWAS_data("rdn1")
merged_sunn1<-merge_GWAS_data("sunn1")
merged_sunn4<-merge_GWAS_data("sunn4")

```

```{r Code for creating overlap plot, echo=FALSE}
# =========================================================
# Overlap analysis: Strain fitness vs Strain fitness shift
# =========================================================

library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)

# -----------------------------
# 1️⃣ Define merged list
# -----------------------------
merged_list <- list(
  A17      = merged_A17,
  dnf1     = merged_dnf1,
  dnf1dnf2 = merged_dnf1dnf2,
  dnf2     = merged_dnf2,
  dnf3     = merged_dnf3,
  dnf4     = merged_dnf4,
  dnf5dnf2 = merged_dnf5dnf2,
  dnf6     = merged_dnf6,
  dnf7     = merged_dnf7,
  hcl      = merged_hcl,
  ipd3     = merged_ipd3,
  latd     = merged_latd,
  nad1     = merged_nad1,
  rdn1     = merged_rdn1,
  sunn1    = merged_sunn1,
  sunn4    = merged_sunn4
)

library(dplyr)
library(ggplot2)


# -----------------------------
# 1️⃣ Define cutoffs
# -----------------------------


##calculate the percent overlap
cutoffs <- c(                    #
             ceiling(0.001 * nrow(merged_A17)))
             

get_overlap <- function(top_n) {

  top_A17 <- merged_A17 %>%
    arrange(pr) %>%
    slice_head(n = top_n) %>%
    pull(ld_snps)

  lapply(names(merged_list), function(host) {

    if (host == "A17") return(NULL)

    top_target <- merged_list[[host]] %>%
      arrange(pr) %>%
      slice_head(n = top_n) %>%
      pull(ld_snps)

    tibble(
      host = host,
      top_n = top_n,
      overlap_n = length(intersect(top_A17, top_target)),
      overlap_pct = overlap_n / length(top_A17) * 100
    )
  }) %>% bind_rows()
}

overlap_all <- lapply(cutoffs, get_overlap) %>% bind_rows()
# -----------------------------
# 2️⃣ Assign proper top_n to strain fitness shift
# -----------------------------

overlap_strainfitnessshift<- read.csv ("../Tables/overlap_df_strainfitness_shift.csv")
overlap_strainfitnessshift <- overlap_strainfitnessshift %>%
  mutate(
    dataset = "Strain fitness shift",
    top_n = rep(cutoffs, each = nrow(overlap_strainfitnessshift)/length(cutoffs))
  )

# -----------------------------
# 3️⃣ Combine datasets
# -----------------------------
combined_overlap_df <- bind_rows(
  overlap_all %>% mutate(dataset = "Strain fitness"),
  overlap_strainfitnessshift
)

# -----------------------------
# 4️⃣ Define host colors
# -----------------------------
hosts <- c(
  "A17", "dnf1", "dnf1dnf2", "dnf2", "dnf3", "dnf4",
  "dnf5dnf2", "dnf6", "dnf7",
  "hcl", "ipd3", "latd", "nad1", "rdn1", "sunn1", "sunn4"
)

host_colors <- c(
  "#0000ff", "#000000", "#5C5A5A", "#feb300", "#00aeae", "#ffff00",
  "#F5E4E4", "#ff4600", "#53a1f0",
  "#e9c6ac", "#9d22f3", "#3d389a", "#95ef57", "#f311c1", "#0a82f0", "#cd93aa"
)
host_color_map <- setNames(host_colors, hosts)

# -----------------------------
# 5️⃣ Create facet labels
# -----------------------------
facet_labels <- setNames(
  c("Top 0.1% SNPs", "Top 1% SNPs", "Top 10% SNPs"),
  as.character(cutoffs)
)

# -----------------------------
# 6️⃣ Convert columns to factors for plotting
# -----------------------------
combined_overlap_df <- combined_overlap_df %>%
  mutate(
    top_n = factor(top_n, levels = cutoffs),
    dataset = factor(dataset, levels = c("Strain fitness", "Strain fitness shift"))
  )

# -----------------------------
# 7️⃣ Plot
# -----------------------------
p <- ggplot(combined_overlap_df, aes(x = dataset, y = overlap_pct)) +
  geom_jitter(
    aes(color = host),
    position = position_jitter(width = 0.3, height = 0),  # slightly wider jitter
    size = 3.0,
    alpha = 0.8,
    stroke = 0.2
  ) +
  scale_color_manual(values = host_color_map, name = "Host") +
  scale_y_continuous(
    limits = c(0, 100),
    expand = expansion(mult = c(0.01, 0.05))
  ) +
  labs(
    y =  "Overlap with A17 within top 0.1% SNPs",
    x = NULL
  ) +
  theme_classic(base_size = 16) +
  theme(
    axis.text.x = element_text(size = 14, angle = 0, hjust = 0.5, vjust = 0.5, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(face = "bold"),
    axis.line = element_line(linewidth = 0.8),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 12),
    panel.grid.major.y = element_line(color = "grey80", linetype = "dashed", linewidth = 0.3),
    panel.grid.minor = element_blank()
  )

# Save as high-res PDF for publication
ggsave(
  filename = "../Figures/strain_overlap_points_top0.1_ISME.pdf",
  plot = p,
  width = 8,
  height = 6,
  dpi = 300
)









```




