---
title: "Mutations in legume symbiosis genes create a complex selective landscape for rhizobial symbionts"
author: Sohini Guha, Regina B. Bledsoe, Jeremy Sutherland, Brendan Epstein, Gwendolyn M. Fry, Nevin D. Young, Peter Tiffin, and Liana T. Burghardt
date: "`r Sys.Date()`"
output: html_document
---

Analysis file for "Mutations in legume symbiosis genes create a complex selective landscape for rhizobial symbionts"

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages needed. 
require(tidyverse)
require(ggpubr)
require(ggplot2)
require(RColorBrewer)
require(gplots)
require(vegan)
require(corrplot)
require(multcomp)
require(purrr)
require(ggrepel)
require(tibble)
require(stringr)
knitr::opts_chunk$set(message = FALSE)
```
###Compiling the data for analysis
```{r Merge all trait data sets, echo=TRUE}
#Names of the Medicago genotypes in A17 background along with their genotype ids, disruption type and order-genotype_name.txt
#Nodule numbers and individual nodule sizes for each sample- data_HostMutants2021_nod_counts.txt
#Sample ids, replicates for each genotype,CFU per ml,aboveground biomass,belowground biomass for each sample-data_nsfpgrp_hostmutants_C86meliloti.txt

# Import the files

# Strain frequency files - freq.tsv
freq_all<-read.table("../data/Strain_frequency.tsv", header=TRUE)
genotype_name <- read.table("../data/Host_genotype.txt",sep = "\t",header=TRUE)

genotype_name<-as_tibble(genotype_name)%>% mutate(across(!order, as.factor)) %>% filter(genotype_id!="838")

# Subset initial inoculum replications and calculate mean fitness across technical replicates
freq_initial<- freq_all %>% filter(str_detect(sample_id, "M_C86_NL")) %>%  dplyr::select(!sample_id) %>% summarise_all(mean)


#Break apart sample_id string into genotype id and replicate and convert into factors
freq_all<-freq_all %>% mutate(genotype_id = substr(sample_id, 3,5), rep = substr(sample_id, 6,6),.before = sample_id) %>% mutate(across(c(genotype_id,rep,sample_id), as.factor))
                                                                                      
 #join the dataset of genotype names with the genotype ids
freq_all <- inner_join(genotype_name,freq_all, by="genotype_id") %>% filter(background=="A17") %>% rename(geno=name)

freq_all$type<-factor(freq_all$type, levels = c("WT","Early","Late","AON"))

freq_all$geno<-factor(freq_all$geno,levels=c("A17", "dmi1-2","dmi2-3","dmi3-1","hcl","ipd3","latd", "nad1", "dnf1", "dnf2","dnf3", "dnf4","dnf6","dnf7", "dnf1/dnf2", "dnf5/dnf2", "rdn1", "sunn1","sunn4"))

#Transform raw frequency data to fitness data= log2(treatment_freq/initial_freq)
fit_all<-as_tibble(cbind(freq_all[,c(1:7)],log2(mapply("/", freq_all[,c(-1:-7)], freq_initial))))

#The lowest fitness values is Mag27 = -7.1 to substitute all INF with -8
fit_all<-fit_all %>% mutate_if(is.numeric, ~ifelse(abs(.) == Inf,-8,.))

#write.table (fit_all,file="../data/Strain Fitness_MedicagoMutants_A17.txt",sep = "\t",row.names = FALSE)

fit_all$geno<-factor(fit_all$geno)
# Create a data frame with fitness means for each geno                            
fit_mean<-fit_all %>% group_by(geno,type) %>% summarise(across(starts_with("MAG"),mean))
fit_median<-fit_all %>% group_by(geno,type) %>% summarise(across(starts_with("MAG"),median))

# Calculate strain diversity and create a new dataset
div_all<-rowwise(freq_all) %>% transmute(geno=geno,type=type, rep=rep,sample_id=substr(sample_id, 3,6), nodule_isolate_diversity=diversity(c_across(starts_with("MAG"))))


data_HostMutants2021_nod_counts <- read.table("../data/data_HostMutants2021_nod_counts.txt",sep = "\t",header=TRUE)

data_nsfpgrp_hostmutants_C86meliloti <- read.table("../data/data_nsfpgrp_hostmutants_C86meliloti.txt",sep = "\t",header=TRUE)
# Merge the datasets sequentially
traits_all <-as_tibble(full_join (data_HostMutants2021_nod_counts,data_nsfpgrp_hostmutants_C86meliloti,by=c("sample_id","genotype_id","rep"))) %>% mutate(across(c(genotype_id,rep),as.factor))

traits_all <-full_join (genotype_name,traits_all,by = "genotype_id") %>% filter(background=="A17")%>% rename(geno=name)

traits_all <- full_join(traits_all,div_all,by=NULL)

###### Data set clean-up ######
# Choose only columns to keep that are meaningful for our analysis
traits_all<-subset (traits_all,select=c(sample_id,genotype_id,geno,type,rep,background,date_biomass_harvested,num_plants,percent_herbivory,flowering,above_biomass_g,below_biomass_g,Count,num_plants_picked_nods,total_area,average_size,cfu_ml,nodule_isolate_diversity))

# Calculate additional measurements
#Rename the traits
traits_all<-traits_all%>% mutate(
  above_biomass_per_plant=above_biomass_g/num_plants,
  below_biomass_per_plant=below_biomass_g/num_plants,
  root_to_shoot_ratio=below_biomass_per_plant/above_biomass_per_plant,
  total_biomass_per_plant=above_biomass_per_plant+below_biomass_per_plant,
  nodule_number_per_plant=Count/num_plants_picked_nods,
  cfu_per_plant_LOG10=log10(cfu_ml/num_plants_picked_nods),
  cfu_per_nodule_LOG10=log10(cfu_ml/Count),
  total_nodulated_area_per_plant=total_area/num_plants_picked_nods,
  average_area_per_nodule=total_nodulated_area_per_plant/nodule_number_per_plant)

#Replacing  'NAN' and 'Inf' with 'NA'
traits_all[is.na(traits_all) | traits_all == "Inf"] <- NA
traits_all[is.na(traits_all) | traits_all == "NaN"] <- NA

#Turning traits_all$type into a factor.
traits_all$type<-factor(traits_all$type, levels = c("WT","Early","Late","AON"))
#Changing the order of the genotypes
traits_all$geno<-factor(traits_all$geno,levels=c("A17", "dmi1-2","dmi2-3","dmi3-1","hcl","ipd3","latd", "nad1", "dnf1", "dnf2","dnf3", "dnf4","dnf6","dnf7", "dnf1/dnf2", "dnf5/dnf2", "rdn1", "sunn1","sunn4"))
#write.table (traits_all,file="../tables/TableS1.txt",sep = "\t",row.names = FALSE)
```
### Statistical Analysis: Coeffecients from ANOVA's and RDAs

```{r Perform analogous RDA Permanova on strain fitness data}
rda_geno<-rda(fit_all[,c(8:93)]~geno+rep,fit_all, scale=TRUE)
rda.model.geno<-anova(rda_geno, step=1000, perm.max=1000, by= "terms")  

rda_type<-rda(fit_all[,c(8:93)]~type+rep,fit_all, scale=TRUE)
rda.model.type<-anova(rda_type, step=1000, perm.max=1000, by= "terms") 

rda.strainfitness<-data.frame(Response=c("nodule_isolate_fitness"),Predictor=c("Genotype","Replicate","Residual","Type","Replicate","Residual"),Sum.Sq=c(rda.model.geno$Variance,rda.model.type$Variance),PctExp=c(rda.model.geno$Variance/sum(rda.model.geno$Variance)*100,rda.model.type$Variance/sum(rda.model.type$Variance)*100),Df=c(rda.model.geno$Df,rda.model.type$Df),Fval=c(rda.model.geno$F,rda.model.type$F), Pval=c(rda.model.geno$`Pr(>F)`,rda.model.type$`Pr(>F)`),R.adj=c(round(RsquareAdj(rda_geno)$adj.r.squared,4),"NA","NA",round(RsquareAdj(rda_type)$adj.r.squared,4),"NA","NA")) 
```

```{r Write Function to run ANOVA and summarize results each Phenotype,echo=TRUE}

extract.anova<- function(trait) {
#Dropping rows with NA

traits_all<-as.data.frame(traits_all[!is.na(traits_all[,trait]),]) 

# Run a model with genotype and replicate as predictors
NodNum.G <- lm(traits_all[,trait] ~ geno + rep, data = traits_all)
# Run a model with type and replicate as predictors
NodNum.T<-lm(traits_all[,trait] ~ type + rep, data = traits_all)
#Examine the Analysis of Variance tables and save output
a.G<-anova(NodNum.G)
a.T<-anova(NodNum.T)

#Compile results into a dataframe
myresults<-data.frame(Response=c(paste(trait)),Predictor=c("Genotype","Replicate","Residual","Type","Replicate","Residual"),Sum.Sq=c(a.G$"Sum Sq",a.T$"Sum Sq"),PctExp=c(a.G$"Sum Sq"/sum(a.G$"Sum Sq")*100,a.T$"Sum Sq"/sum(a.T$"Sum Sq")*100),Df=c(a.G$"Df",a.T$"Df"),Fval=c(a.G$"F value",a.T$"F value"), Pval=c(a.G$"Pr(>F)",a.T$"Pr(>F)"),R.adj=c(summary(NodNum.G)$adj.r.squared,"NA","NA",summary(NodNum.T)$adj.r.squared,"NA","NA"))

return(myresults)

}

#Compile Anova results across Traits
ANOVA.Trait.Summary<-rbind(extract.anova("nodule_number_per_plant"),extract.anova("average_area_per_nodule"),extract.anova("total_nodulated_area_per_plant"),extract.anova("total_biomass_per_plant"),extract.anova("root_to_shoot_ratio"),extract.anova("cfu_per_nodule_LOG10"),extract.anova("cfu_per_plant_LOG10"),extract.anova("nodule_isolate_diversity"),rda.strainfitness)

write.table (ANOVA.Trait.Summary,file="../tables/TableS2.txt",sep = "\t",row.names = FALSE)
```

```{r Write Function to calculate Tukey and summarize results each Phenotype, echo=TRUE}

cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442")
traits_to_plot <- c(
  "nodule_number_per_plant",
  "total_nodulated_area_per_plant",
  "average_area_per_nodule",
  "root_to_shoot_ratio",
  "total_biomass_per_plant",
  "cfu_per_nodule_LOG10",
  "cfu_per_plant_LOG10",
  "nodule_isolate_diversity"
)

trait_boxplot_with_tukey_fdr_A17 <- function(trait, trait_all, mypal = cbPalette, log_transform = TRUE) {
  if (!trait %in% colnames(trait_all)) {
    stop(paste("Trait column", trait, "not found in data"))
  }
  
  data_clean <- trait_all %>%
    filter(!is.na(type), !is.na(geno), !is.na(.data[[trait]])) %>%
    mutate(
      geno = factor(geno, levels = rev(levels(factor(geno)))),
      type = droplevels(factor(type))
    )
  
  data_clean <- data_clean %>%
    mutate(mytrait = if (log_transform) log10(.data[[trait]] + 1e-6) else .data[[trait]])
  
  aov_model <- aov(mytrait ~ geno, data = data_clean)
  tukey <- TukeyHSD(aov_model)
  tukey_df <- as.data.frame(tukey$geno)
  tukey_df$comparison <- rownames(tukey_df)
  
  # Filter only comparisons involving "A17"
  tukey_df <- tukey_df %>% filter(str_detect(comparison, "A17"))
  
  # Prepare Tukey p_adj and significance stars
  tukey_df <- tukey_df %>%
    mutate(
      trait = trait,
      p_adj = `p adj`,
      Significant = case_when(
        p_adj < 0.001 ~ "***",
        p_adj < 0.01 ~ "**",
        p_adj < 0.05 ~ "*",
        TRUE ~ ""
      )
    )
  
  # Extract other genotype from comparison for labeling
  tukey_labels <- tukey_df %>%
    mutate(
      other_geno = ifelse(grepl("^A17-", comparison),
                          sub("A17-", "", comparison),
                          sub("-A17", "", comparison))
    ) %>%
    filter(Significant != "")
  
  label_data <- data_clean %>%
    group_by(geno) %>%
    summarize(y = max(mytrait, na.rm = TRUE)) %>%
    inner_join(tukey_labels, by = c("geno" = "other_geno"))
  
  p <- ggplot(data_clean, aes(x = geno, y = mytrait, fill = type)) +
    geom_boxplot(outlier.shape = NA, coef = 0) +
    geom_jitter(width = 0.2, alpha = 0.6) +
    coord_flip() +
    scale_fill_manual(values = mypal, na.translate = FALSE) +
    labs(x = "Plant Host", y = ifelse(log_transform, paste0("log10(", trait, ")"), trait)) +
    theme_classic() +
    theme(legend.position = "top", text = element_text(size = 18))
  
  if (nrow(label_data) > 0) {
    p <- p + geom_text(data = label_data,
                       aes(x = geno, y = y + 0.05 * max(data_clean$mytrait), label = Significant),
                       inherit.aes = FALSE,
                       size = 6)
  }
  
  list(plot = p, tukey_df = tukey_df)
}

all_tukey_results <- data.frame()

pdf("../figures/traitswithTukey_A17only_stars_log10.pdf", width = 9, height = 9)
for (t in traits_to_plot) {
  res <- trait_boxplot_with_tukey_fdr_A17(trait = t, trait_all = traits_all, log_transform = TRUE)
  print(res$plot)
  all_tukey_results <- bind_rows(all_tukey_results, res$tukey_df)
}
dev.off()

write.table(all_tukey_results, "../tables/TableS3_log10.tsv",sep = "\t", quote = FALSE, row.names = FALSE)

##No transformation

trait_boxplot_with_tukey_fdr_A17_noTransform <- function(trait, trait_all, mypal = cbPalette, log_transform = FALSE) {
  if (!trait %in% colnames(trait_all)) {
    stop(paste("Trait column", trait, "not found in data"))
  }
  
  data_clean <- trait_all %>%
    filter(!is.na(type), !is.na(geno), !is.na(.data[[trait]])) %>%
    mutate(
      geno = factor(geno, levels = rev(levels(factor(geno)))),
      type = droplevels(factor(type))
    )
  
  data_clean <- data_clean %>%
    mutate(mytrait = if (log_transform) log2(.data[[trait]] + 1e-6) else .data[[trait]])
  
  aov_model <- aov(mytrait ~ geno, data = data_clean)
  tukey <- TukeyHSD(aov_model)
  tukey_df <- as.data.frame(tukey$geno)
  tukey_df$comparison <- rownames(tukey_df)
  
  # Filter only comparisons involving "A17"
  tukey_df <- tukey_df %>% filter(str_detect(comparison, "A17"))
  
  # Prepare Tukey p_adj and significance stars
  tukey_df <- tukey_df %>%
    mutate(
      trait = trait,
      p_adj = `p adj`,
      Significant = case_when(
        p_adj < 0.001 ~ "***",
        p_adj < 0.01 ~ "**",
        p_adj < 0.05 ~ "*",
        TRUE ~ ""
      )
    )
  
  
  # Extract other genotype from comparison for labeling
  tukey_labels <- tukey_df %>%
    mutate(
      other_geno = ifelse(grepl("^A17-", comparison),
                          sub("A17-", "", comparison),
                          sub("-A17", "", comparison))
    ) %>%
    filter(Significant != "")
  
  label_data <- data_clean %>%
    group_by(geno) %>%
    summarize(y = max(mytrait, na.rm = TRUE)) %>%
    inner_join(tukey_labels, by = c("geno" = "other_geno"))
  
  p <- ggplot(data_clean, aes(x = geno, y = mytrait, fill = type)) +
    geom_boxplot(outlier.shape = NA, coef = 0) +
    geom_jitter(width = 0.2, alpha = 0.6) +
    coord_flip() +
    scale_fill_manual(values = mypal, na.translate = FALSE) +
    labs(x = "Plant Host", y = trait) +
    theme_classic() +
    theme(legend.position = "top", text = element_text(size = 18))
  
  if (nrow(label_data) > 0) {
    p <- p + geom_text(data = label_data,
                       aes(x = geno, y = y + 0.05 * max(data_clean$mytrait), label = Significant),
                       inherit.aes = FALSE,
                       size = 6)
  }
  
  list(plot = p, tukey_df = tukey_df)
}

# Example usage without transformation:
all_tukey_results_noTransform <- data.frame()

pdf("../figures/traitswithTukey_A17only_stars_noTransform.pdf", width = 9, height = 9)
for (t in traits_to_plot) {
  res <- trait_boxplot_with_tukey_fdr_A17_noTransform(trait = t, trait_all = traits_all, log_transform = FALSE)
  print(res$plot)
  all_tukey_results_noTransform <- bind_rows(all_tukey_results_noTransform, res$tukey_df)
}
dev.off()

write.table(all_tukey_results_noTransform,"../tables/TableS3.tsv",sep = "\t", quote = FALSE, row.names = FALSE)

#Tukey across the disruption stages

run_tukey <- function(trait) {
  data <- traits_all %>%
    filter(!is.na(type), !is.na(.data[[trait]])) %>%
    mutate(type = droplevels(factor(type)))

  aov_result <- aov(formula(paste(trait, "~ type")), data = data)
  tukey <- TukeyHSD(aov_result)

  tukey_df <- as.data.frame(tukey$type) %>%
    rownames_to_column("comparison") %>%
    mutate(
      groups = strsplit(comparison, "-"),
      groups_sorted = purrr::map_chr(groups, ~ paste(sort(.x), collapse = "-"))
    )

  tukey_df_filtered <- tukey_df %>%
    filter(groups_sorted %in% c("AON-Early", "Early-Late", "AON-Late")) %>%
    dplyr::select(-groups, -groups_sorted) %>%  
    mutate(
      trait = trait,
      Signif = case_when(
        `p adj` < 0.001 ~ "***",
        `p adj` < 0.01  ~ "**",
        `p adj` < 0.05  ~ "*",
        TRUE            ~ ""
      )
    )

  if (nrow(tukey_df_filtered) == 0) return(data.frame())
  return(tibble::as_tibble(tukey_df_filtered))
}

# Run it
tukey_results_type <- purrr::map_dfr(traits_to_plot, run_tukey)

# View and export
print(tukey_results_type, row.names = FALSE)
write.csv(tukey_results_type, file = "../tables/tukey_type_stage_comparisons.csv", row.names = FALSE)

```



```{r RDA Model results for Strain Isolate Fitness}

extract.rda<-function(mygroup, predictor="geno", p.threshold=0.05) {

#Step 1: Remove all genotypes but the focal genotype and WT  

if(predictor=="geno")  {
  fit_sub<-fit_all[fit_all$geno==mygroup|fit_all$geno=="A17",] 
  rda_model<-rda(fit_sub[,c(8:93)]~geno,fit_sub, scale=TRUE)
  rda_anova<-anova(rda_model, step=1000, perm.max=1000, by= "terms") 
}  

if(predictor=="type")  {
  fit_sub<-fit_all[fit_all$type==mygroup|fit_all$type=="WT",] 
  rda_model<-rda(fit_sub[,c(8:93)]~type,fit_sub, scale=TRUE)
  rda_anova<-anova(rda_model, step=1000, perm.max=1000, by= "terms")  
}  

my.coefs <-data.frame(Trait="nodule_isolate_fitness",Predictor=paste(mygroup),R.adj=c(round(RsquareAdj(rda_model)$adj.r.squared,4)),Prop.Var=round(rda_anova[1,"Variance"]/sum(rda_anova$Variance),4), f.value=rda_anova[1,"F"],P.value=round(rda_anova [1,"Pr(>F)"],4),Class="None") 

# Step 6 Modify catagorizations based on coef and pvalue. 
  try(my.coefs[(my.coefs$P.value< p.threshold),]$Class<-"Change") 
  
return(my.coefs)

}  
# Compile results for Genotype RDA's
Geno.Coef.RDA<-rbind(extract.rda("hcl"),extract.rda("ipd3"),extract.rda("latd"),extract.rda("nad1"),extract.rda("dnf1"),extract.rda("dnf2"),extract.rda("dnf3"),extract.rda("dnf4"),extract.rda("dnf6"),extract.rda("dnf7"),extract.rda("dnf1/dnf2"),extract.rda("dnf5/dnf2"),extract.rda("rdn1"),extract.rda("sunn1"),extract.rda("sunn4"))

Type.Coef.RDA<-rbind(extract.rda("AON",predictor="type"),extract.rda("Early",predictor = "type"),extract.rda("Late",predictor = "type"))

write.table (Type.Coef.RDA,file="../tables/TableS4.txt",sep = "\t",row.names = FALSE)
write.table (Geno.Coef.RDA,file="../tables/TableS5.txt",sep = "\t",row.names = FALSE)


```

###Visualizing Results


```{r Code for creating FigS1 and FigS3, echo=TRUE}


# Graph the initial frequency histogram
hist(t(freq_initial),breaks = 10, main= "Initial strain frequency distribution")

pdf(file = "../figures/FigS1.pdf",width = 6, height = 6)
hist(t(freq_initial),breaks = 10, main= "Initial strain frequency distribution", xlab="Isolate Frequency", ylab="Number of Isolates")
dev.off()



fit_all$geno<-factor(fit_all$geno)
# Create a data frame with fitness means for each geno                            
fit_mean<-fit_all %>% group_by(geno,type) %>% summarise(across(starts_with("MAG"),mean))
fit_median<-fit_all %>% group_by(geno,type) %>% summarise(across(starts_with("MAG"),median))

# Calculate strain diversity and create a new dataset
div_all<-rowwise(freq_all) %>% transmute(geno=geno,type=type, rep=rep,sample_id=substr(sample_id, 3,6), nodule_isolate_diversity=diversity(c_across(starts_with("MAG"))))
pdf(file = "../figures/FigS3.pdf",width = 6, height = 6)
##rank order shifts


# 1. Reshape to long format (strain-wise fitness)
long_freq <- freq_all %>%
  pivot_longer(
    cols = starts_with("MAG"),
    names_to = "strain",
    values_to = "fitness"
  )

# 2. Compute median fitness per strain-genotype
median_fitness <- long_freq %>%
  group_by(geno, strain) %>%
  summarize(median_fitness = median(fitness, na.rm = TRUE), .groups = "drop")

# 3. Rank strains within each genotype (lower rank = higher fitness)
ranked_fitness <- median_fitness %>%
  group_by(geno) %>%
  mutate(rank = dense_rank(desc(median_fitness))) %>%
  ungroup()

# 4. Get all unique genotypes and strains
all_genos <- unique(ranked_fitness$geno)
all_strains <- unique(ranked_fitness$strain)

# 5. Create full grid to ensure all genotype-strain combinations exist
full_grid <- expand_grid(geno = all_genos, strain = all_strains)

# 6. Join to fill in NAs for missing combinations
ranked_fitness_complete <- full_grid %>%
  left_join(ranked_fitness, by = c("geno", "strain"))

# 7. Order strains by their rank in A17 (for y-axis ordering)
a17_order <- ranked_fitness %>%
  filter(geno == "A17") %>%
  arrange(rank) %>%
  pull(strain) %>%
  unique()

# 8. Final dataset for plotting
ranked_plot_data <- ranked_fitness_complete %>%
  mutate(strain = factor(strain, levels = rev(a17_order)))

# 9. Plot: gray = all genotypes, blue = A17
ggplot(ranked_plot_data, aes(x = rank, y = strain)) +
  
  # Gray points for all genotypes except A17
  geom_point(
    data = filter(ranked_plot_data, geno != "A17"),
    alpha = 0.3, size = 1.5, color = "gray40"
  ) +
  
  # Blue points for A17
  geom_point(
    data = filter(ranked_plot_data, geno == "A17"),
    size = 1.5, color = "#0072B2"
  ) +

  # Reverse x-axis so best fitness ranks (1) appear left
  scale_x_reverse(limits = c(max(ranked_fitness$rank, na.rm = TRUE), 1), expand = c(0.01, 0.01)) +
  
  # Theme suitable for publication
  theme_classic(base_size = 8) +
  theme(
    axis.text.y = element_text(size = 6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(size = 7),
    plot.title = element_text(size = 8, face = "bold"),
    panel.grid = element_blank(),
    axis.ticks.length = unit(0.15, "cm")
  ) +

  # Labels
  labs(
    title = "Rank of Sinorhizobium Strains Across Host Genotypes",
    x = "Relative Fitness Rank",
    y = NULL
  )

dev.off()
```
```{r Code for creating Fig5B and Fig S2,echo=TRUE}
df1  <- data.frame(geno=fit_all$geno,type=fit_all$type,summary(rda_geno)$site)    
rda1_ev <-as.vector(eigenvals(rda_geno, model = c("constrained")))

rdainfo<-data.frame(geno=levels(factor(fit_all$geno)),mycols=c("#B23214","#56B4E9","#56B4E9","#56B4E9","#009E73","#009E73","#009E73","#009E73","#009E73","#009E73","#009E73","#009E73","#009E73","#E69F00","#E69F00","#E69F00"), myshapes=c(19,19,18,17,19,18,17,1,2,3,4,5,6,19,18,17))

pdf(file = "../figures/FigS2.pdf",width = 5, height = 5)

ggplot(df1, aes(x=RDA1,y=RDA2,color=type))+
  scale_color_manual(values=cbPalette)+
  geom_text(aes(label=geno),size=3)+stat_ellipse(aes(group = geno), linetype = "solid", alpha = 0.3)+geom_hline(yintercept=0, linetype="dotted") +
  geom_vline(xintercept=0, linetype="dotted") +
  labs(x=paste("RDA 1 (",round(rda1_ev[1],2),"%)"),y=paste("RDA 2 (",round(rda1_ev[2],2),"%)"), color="Type") +
  theme_classic() + theme(legend.position="top", text = element_text(size=12))

ggplot(df1, aes(x=RDA3,y=RDA4,color=type))+
  scale_color_manual(values=cbPalette)+
  geom_text(aes(label=geno),size=3) +
  geom_hline(yintercept=0, linetype="dotted") +
  geom_vline(xintercept=0, linetype="dotted") +
  labs(x=paste("RDA 3 (",round(rda1_ev[3],2),"%)"),y=paste("RDA 4 (",round(rda1_ev[4],2),"%)"), color="Type") +
  theme_classic() + theme(legend.position="top", text = element_text(size=12)) 



# Define color palette
cbPalette <- c("#B23214", "#56B4E9", "#009E73", "#E69F00")  # Update as needed

pdf(file = "../figures/Fig5B.pdf",width = 9, height = 9)
rda_summary <- df1 %>% group_by(geno) %>%summarise(mean_RDA1 = mean(RDA1), mean_RDA2 = mean(RDA2))
traits_all.2<-traits_all%>%dplyr:: select(-sample_id,-rep,-genotype_id,-background,-date_biomass_harvested,-num_plants,-average_size,-percent_herbivory,-flowering,-num_plants_picked_nods,-above_biomass_g,-type,-below_biomass_g,-cfu_ml,-type,-Count,-total_area,-below_biomass_per_plant,-above_biomass_per_plant,-total_area)%>%group_by(geno)%>%summarise_if(is.numeric, mean, na.rm = TRUE)%>%filter(!geno %in% c("dmi1-2", "dmi2-3", "dmi3-1", "skl"))
traits_all.3<-left_join(traits_all.2, rda_summary, by = "geno")
traits_all.3<-as.matrix(traits_all.3[,-1])
correlation_matrix <- cor(traits_all.3, method = "pearson", use = "pairwise.complete.obs")

# Step 1: Compute correlation matrix
correlation_matrix_reordered <- cor(traits_all.3, method = "pearson", use = "pairwise.complete.obs")

# Step 2: Define custom order
custom_order <- c(
  "cfu_per_nodule_LOG10",
  "cfu_per_plant_LOG10",
  "nodule_isolate_diversity",
  "mean_RDA1",
  "mean_RDA2",
  "nodule_number_per_plant",
  "total_nodulated_area_per_plant",
  "average_area_per_nodule",
  "total_biomass_per_plant",
  "root_to_shoot_ratio"
)

# Step 3: Define renamed labels (corrected)
custom_order_renamed <- c(
  "cfu_per_nodule_LOG10" = "CFU/nodule",
  "cfu_per_plant_LOG10" = "CFU/plant",
  "nodule_isolate_diversity" = "Nodule strain diversity",
  "mean_RDA1" = "Strain Composition (RDA1)",
  "mean_RDA2" = "Strain Composition (RDA2)",
  "nodule_number_per_plant" = "Nodules/plant",
  "total_nodulated_area_per_plant" = "Total nodulated area/plant",
  "average_area_per_nodule" = "Average area/nodule",
  "total_biomass_per_plant" = "Total biomass/plant",
  "root_to_shoot_ratio" = "Root-to-shoot ratio"
)

# Apply new names directly to the matrix
rownames(correlation_matrix_reordered) <- custom_order_renamed[custom_order]
colnames(correlation_matrix_reordered) <- custom_order_renamed[custom_order]

# Now plot
corrplot(correlation_matrix_reordered,
         method = "ellipse",
         type = "upper",
         addCoef.col = "black",
         number.cex = 0.8,
         tl.col = "black",
         tl.srt = 45,
         diag = FALSE)

dev.off()
```

```{r Code for creating Fig 5A, echo=FALSE}

# Load required libraries


# --- Define custom color palette ---
cbPalette <- c("#B23214", "#56B4E9", "#009E73", "#E69F00")
pdf(file = "../figures/Fig 5A.pdf", width = 15, height = 12)

# --- Traits to use ---
traits_to_use <- c(
  "nodule_number_per_plant",
  "total_nodulated_area_per_plant",
  "average_area_per_nodule",
  "root_to_shoot_ratio",
  "total_biomass_per_plant",
  "cfu_per_nodule_LOG10",
  "cfu_per_plant_LOG10",
  "nodule_isolate_diversity"
)

# --- Step 1: Average 'latd' and 'rdn1' across pots ---
avg_genos <- traits_all %>%
  filter(geno %in% c("latd", "rdn1")) %>%
  group_by(geno, type) %>%
  summarise(across(all_of(traits_to_use), mean, na.rm = TRUE), .groups = "drop")

# --- Step 2: Keep all other genotypes unaveraged ---
other_genos <- traits_all %>%
  filter(!geno %in% c("latd", "rdn1"))

# --- Step 3: Combine averaged genotypes with other genotypes ---
traits_combined <- bind_rows(avg_genos, other_genos)

# --- Step 4: RDA summary per genotype ---
rda_summary <- df1 %>%
  group_by(geno) %>%
  summarise(
    mean_RDA1 = mean(RDA1, na.rm = TRUE),
    mean_RDA2 = mean(RDA2, na.rm = TRUE),
    .groups = "drop"
  )

# --- Step 5: Merge RDA + log-transform traits ---
traits_with_rda <- traits_combined %>%
  left_join(rda_summary, by = "geno") %>%
  mutate(across(all_of(traits_to_use), ~ log2(. + 1e-6))) %>%
  tidyr::drop_na(all_of(c(traits_to_use, "mean_RDA1", "mean_RDA2")))

# --- Step 6: PCA input matrix ---
pca_input <- dplyr::select(traits_with_rda, all_of(traits_to_use), mean_RDA1, mean_RDA2)

# --- Step 7: PCA run ---
pca_result <- prcomp(pca_input, center = TRUE, scale. = TRUE)
var_explained <- (pca_result$sdev)^2 / sum((pca_result$sdev)^2)

# --- Step 8: Sample scores (PC1/PC2) ---
pca_coords <- data.frame(pca_result$x[, 1:2]) %>%
  mutate(
    geno = traits_with_rda$geno,
    type = traits_with_rda$type
  )

# --- Step 9: Trait loadings for biplot arrows ---
loadings <- data.frame(pca_result$rotation[, 1:2]) %>%
  rownames_to_column("trait") %>%
  mutate(trait = recode(trait,
    cfu_per_nodule_LOG10 = "CFU/nodule",
    cfu_per_plant_LOG10 = "CFU/plant",
    nodule_number_per_plant = "Nodules/plant",
    total_nodulated_area_per_plant = "Total nodulated area/plant",
    average_area_per_nodule = "Average area/nodule",
    total_biomass_per_plant = "Biomass/plant",
    root_to_shoot_ratio = "Root-to-shoot ratio",
    nodule_isolate_diversity = "Nodule strain diversity",
    mean_RDA1 = "Strain Composition (RDA1)",
    mean_RDA2 = "Strain Composition (RDA2)"
  ))

# --- Step 10: Plot PCA biplot ---
arrow_mult <- 5
label_mult <- 6

ggplot(pca_coords, aes(x = PC1, y = PC2, color = type)) +
  geom_vline(xintercept = 0, color = "gray60", linetype = "dashed") +
  geom_hline(yintercept = 0, color = "gray60", linetype = "dashed") +
  # Removed geom_point(size = 3, alpha = 0.85)
  ggrepel::geom_text_repel(
    aes(label = geno),
    size = 5,
    max.overlaps = Inf,
    box.padding = 0.6,
    point.padding = 0.5,
    segment.size = NA
  ) +
  geom_segment(data = loadings,
               aes(x = 0, y = 0, xend = PC1 * arrow_mult, yend = PC2 * arrow_mult),
               arrow = arrow(length = unit(0.3, "cm")),
               color = "black",
               linewidth = 0.7) +
  geom_text(data = loadings,
            aes(x = PC1 * label_mult, y = PC2 * label_mult, label = trait),
            hjust = 0.3, vjust = -0.3,
            size = 5,
            color = "black") +
  coord_fixed() +
  scale_color_manual(values = cbPalette) +
  labs(
    title = "PCA Biplot: Plant Traits + RDA (latd and rdn1 averaged only)",
    x = paste0("PC1 (", round(var_explained[1] * 100, 1), "% variance)"),
    y = paste0("PC2 (", round(var_explained[2] * 100, 1), "% variance)"),
    color = "Type"
  ) +
  theme_classic(base_size = 16) +
  theme(
    axis.line = element_line(color = "black", linewidth = 0.6),
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13)
  )


dev.off()
```


```{r Code for creating Fig2A-D and FigS6, echo=TRUE}

cbPalette <- c("#B23214","#56B4E9", "#009E73", "#E69F00")

trait.boxplot <- function(trait, mypal = cbPalette, log = FALSE, trait_all = traits_all) {
  if (!trait %in% colnames(trait_all)) {
    stop(paste("The specified trait column", trait, "does not exist in the data frame."))
  }
  
  # Replace NA with 0 for numeric columns
 trait_all <- trait_all %>% mutate(across(where(is.numeric), ~.))

 # trait_all <- trait_all %>%
    #mutate(across(where(is.numeric), ~replace(., is.na(.), 0)))
  
  # Filter out rows with NA in 'type', 'geno', or the focal trait
  trait_all <- trait_all %>%
    filter(!is.na(type), !is.na(geno), !is.na(trait_all[[trait]])) %>%
    mutate(
      geno = factor(geno, levels = rev(levels(factor(geno)))),  # Reverse the order of factor levels for 'geno'
      type = droplevels(factor(type))
    )
  
  # Create a subset data frame for the focal trait
  mydata <- data.frame(
    geno = trait_all$geno,
    type = trait_all$type,
    mytrait = trait_all[[trait]]
  )
  
  # Base Plot
  plot <- ggplot(mydata, aes(x = geno, y = mytrait, fill = type)) +
    geom_boxplot(outlier.shape = NA, na.rm = TRUE, coef = 0) +
    geom_jitter(na.rm = TRUE) +
    coord_flip() +  # Flip coordinates (for horizontal layout)
    scale_fill_manual(values = mypal, na.translate = FALSE) + # Prevent 'NA' in the legend
    labs(x = "Plant Host", y = trait) +
    theme_classic() +
    theme(legend.position = "top", text = element_text(size = 18))
  
  # Custom y-axis for specific traits
  if (trait == "nodule_isolate_diversity") {
    plot <- plot + scale_y_continuous(
      breaks = seq(3.5, 4.5, by = 0.25),  # Define breaks: 3.5, 3.75, 4.0, 4.25, 4.5
      limits = c(3.5, 4.5)                # Set limits for the y-axis
    )
  } else if (trait == "cfu_per_nodule_LOG10") {
    plot <- plot + scale_y_continuous(
      breaks = seq(4.5, 6.5, by = 0.5),  # Define breaks: 5, 5.5, 6, 6.5
      limits = c(4.5, 6.5)               # Set limits for the y-axis
    )
  } else if (trait == "cfu_per_plant_LOG10") {
    plot <- plot + scale_y_continuous(
      breaks = seq(7, 9.5, by = 0.5),  # Define breaks: 7, 7.5, 8, 8.5, 9
      limits = c(7, 9.5)               # Set limits for the y-axis
    )
  }
  
  return(plot)
}




pdf(file = "../figures/Fig2A-D.pdf",width = 6, height = 6)
trait.boxplot(trait = "cfu_per_nodule_LOG10",trait_all = traits_all[!traits_all$geno %in% c("dmi1-2", "dmi2-3", "dmi3-1"), ])
trait.boxplot(trait = "cfu_per_plant_LOG10",trait_all = traits_all[!traits_all$geno %in% c("dmi1-2", "dmi2-3", "dmi3-1","latd"), ])
trait.boxplot(trait = "nodule_isolate_diversity",trait_all = traits_all[!traits_all$geno %in% c("dmi1-2", "dmi2-3", "dmi3-1"), ])
dev.off()

pdf(file = "../figures/FigS6.pdf",width = 6, height = 6)
trait.boxplot(trait = "nodule_number_per_plant")
trait.boxplot(trait = "total_nodulated_area_per_plant", trait_all = traits_all[!traits_all$geno %in% c("dmi1-2", "dmi2-3", "dmi3-1"), ])
trait.boxplot(trait = "average_area_per_nodule",trait_all = traits_all[!traits_all$geno %in% c("dmi1-2", "dmi2-3", "dmi3-1"), ])
trait.boxplot(trait = "root_to_shoot_ratio")
trait.boxplot(trait = "total_biomass_per_plant")
dev.off()

```

```{r Code for creating Fig2E, echo=TRUE}

pal = colorRampPalette(c('#2166AC',"#89ADD0", '#F7F7F7', '#B2182B'))(length(seq(-7.9, 4, 0.1)))
#pal = colorRampPalette(c('#2166AC','#F7F7F7', '#B2182B'))(length(seq(-7.9, 4, 0.1)))


col_letters = c("A17"="#B23214","hcl"="#56B4E9","ipd3"="#56B4E9","latd"="#56B4E9", "nad1"="#009E73", "dnf1"="#009E73", "dnf2"="#009E73","dnf3"="#009E73", "dnf4"="#009E73","dnf6"="#009E73","dnf7"="#009E73", "dnf1/dnf2"="#009E73", "dnf5/dnf2"="#009E73", "rdn1"="#E69F00", "sunn1"="#E69F00","sunn4"="#E69F00")

fit_mean_matrix<-fit_mean %>% dplyr::select(!type) %>% column_to_rownames(var="geno")
fit_median_matrix<-fit_median %>% dplyr::select(!type) %>% column_to_rownames(var="geno")
write.table (fit_median_matrix,file="../tables/Relative_strainfitness.txt",sep = "\t",row.names = FALSE)
pdf(file = "../figures/Fig2E.pdf",width = 5, height = 10)
heatmap.2(t(as.matrix(fit_mean_matrix)),Rowv=TRUE, Colv=TRUE,dendrogram = "both", col=pal,hclustfun = function(d) hclust(d,method="ward.D2"),trace="none", scale="none",cexCol = 1,cexRow = .5, key=TRUE,key.xlab = "Mean Fitness", key.ylab =NA, tracecol="black",symbreaks=FALSE,key.title = NA,colCol = col_letters) #color key helps me understand the dynamics.

heatmap.2(t(as.matrix(fit_median_matrix)),Rowv=TRUE, Colv=TRUE, dendrogram = "both",col=pal,hclustfun = function(d) hclust(d,method="ward.D2"), trace="none", scale="none", cexCol = 1,cexRow = .5, key=TRUE,key.xlab = "Median Fitness", key.ylab =NA , tracecol="black",symbreaks=FALSE,key.title = NA,colCol = col_letters)

myorder<-order(rank(fit_mean_matrix["A17",]))
heatmap1<-heatmap.2(t(as.matrix(fit_mean_matrix[,myorder])),Rowv=FALSE, Colv=TRUE, dendrogram = "column", hclustfun = function(d) hclust(d,method="ward.D2"), col=pal, trace="none", scale="none", cexCol = 1,cexRow = .5, key=TRUE,key.xlab = "Mean Fitness", key.ylab =NA , tracecol="black",symbreaks=FALSE, key.title = NA,colCol = col_letters)


myorder<-order(rank(fit_median_matrix["A17",]))
heatmap.2(t(as.matrix(fit_median_matrix[,myorder])),Rowv=FALSE, Colv=TRUE, dendrogram = "column", hclustfun = function(d) hclust(d,method="ward.D2"),col=pal, trace="none", scale="none", cexCol = 1,cexRow = .5, key=TRUE,key.xlab = "Median Fitness", key.ylab =NA , tracecol="black",symbreaks=FALSE, key.title = NA,colCol = col_letters)


dev.off()

```



```{R Code for creating Fig3A,echo=TRUE}
pdf(file = "../figures/Fig3A.pdf",width = 5.75, height = 12)
x<- as_tibble(t(fit_median_matrix)) 
# Choices "latd","ipd3", "nad1","dnf2","dnf3","dnf6","dnf7","sunn4" 

GWAS_traits<-tibble(strains=row.names(t(fit_mean_matrix)),latd=x$latd-x$A17,ipd3=x$ipd3-x$A17,nad1=x$nad1-x$A17,dnf2=x$dnf2-x$A17,dnf3=x$dnf3-x$A17,dnf6=x$dnf6-x$A17,dnf7=x$dnf7-x$A17,sunn4=x$sunn4-x$A17,sunn1=x$sunn1-x$A17,rdn1=x$rdn1-x$A17,hcl=x$hcl-x$A17,dnf1=x$dnf1-x$A17,dnf4=x$dnf4-x$A17,dnf5dnf2=x$`dnf5/dnf2`-x$A17,dnf1dnf2=x$`dnf1/dnf2`-x$A17)

write.table (GWAS_traits,file="../tables/Mean_strainfitnessshift.txt",sep = "\t",row.names = FALSE)


#Creating the heatmap for the strain fitness shifts

data <- GWAS_traits
# Omit the "strains" column
GWAS_traits <- GWAS_traits[, !colnames(GWAS_traits) %in% "strains"]
GWAS_traits <- as.matrix(sapply(GWAS_traits, as.numeric))
row.names(GWAS_traits) <- data$strains



# Enhanced color palette with more colors for more variation
#pal <- colorRampPalette(c('#2166AC', '#3C8D99', '#6A9DC4', '#B2D7E8', '#F7F7F7', '#F4A582', '#D95F30', '#B2182B', '#660001'))(100)
#pal <- colorRampPalette(c('#2166AC', '#3C8D99', '#6A9DC4', '#B2D7E8', '#F7F7F7', '#D6604D', '#B2182B', '#660001'))(100)
pal <- colorRampPalette(c('#542788', '#8073AC', '#B2ABD2', '#F7F7F7', '#FDB863', '#E08214', '#B35806', '#7F3B08'))(100)

#pal = colorRampPalette(c('#2166AC',"#89ADD0", '#F7F7F7', '#B2182B'))(100)

# Modify the breaks to span a wider range for smoother transitions between colors
breaks <- seq(-3, 3, length.out = length(pal) + 1)


# Define custom column colors (this remains the same as in your previous example)
col_letters = c("A17"="#B23214", "hcl"="#56B4E9", "ipd3"="#56B4E9", 
                "latd"="#56B4E9", "nad1"="#009E73", "dnf1"="#009E73", 
                "dnf2"="#009E73", "dnf3"="#009E73", "dnf4"="#009E73", 
                "dnf6"="#009E73", "dnf7"="#009E73", "dnf1dnf2"="#009E73", 
                "dnf5dnf2"="#009E73", "rdn1"="#E69F00", "sunn1"="#E69F00", 
                "sunn4"="#E69F00")
# Map the colors from col_letters to the columns in GWAS_traits
column_colors <- col_letters[colnames(GWAS_traits)]

# Plot the heatmap with the updated color palette and breaks for more variation
heatmap.2(GWAS_traits, 
          trace = "none",  # No trace lines inside the heatmap
          density.info = "density",  # Add density plot in the key
          breaks = breaks,  # Define the breaks for the color scale
          col = pal,  # Use the updated color palette
          Rowv = TRUE, 
          Colv = TRUE, 
          dendrogram = "col",  # Show column dendrogram only (adjust as needed)
          hclustfun = function(d) hclust(d, method = "ward.D2"),  # Clustering method
          scale = "none",  # Do not scale the data (or use "row" if you want normalization)
          cexCol = 1,  # Adjust column label size
          cexRow = 0.6,  # Adjust row label size
          key = TRUE,  # Show color scale
          key.xlab = "Fitness Shifts",  # Label for the key's x-axis
          key.ylab = NA,  # No label for the key's y-axis
          tracecol = "black",  # Color of trace lines (if any)
          symbreaks = FALSE,  # Do not use symmetric breaks
          key.title = NA,  # No title for the key
          colCol = column_colors,  # Apply the correct colors to columns
          keysize = 1.2,  # Adjust key size
          margins = c(10, 10))  # Adjust margins to accommodate row labels

dev.off()

```

```{R Subset data for testing the malonylCOA mutant in A17, sunn4, dnf7 and dnf3}
df <- read.csv("~/Library/CloudStorage/OneDrive-ThePennsylvaniaStateUniversity/Sohini&Liana/GitHub/HostMutants2021_C86meliloti/data/Pervasivegene_MalonylCOA_validation.csv")

pdf(file = "../figures/Pervasivegene_validationplots.pdf",width = 4, height = 4)


#With the initial culture as a seperate columne

# Subset relevant columns
df2 <- df %>% dplyr::select(Host, Trt, LBMC, LBMC.gent.60.)

# Clean the data: replace "#DIV/0!" with NA and convert LBMC & LBMC.gent.60. to numeric
df2$LBMC <- as.numeric(ifelse(df2$LBMC == "#DIV/0!", NA, df2$LBMC))
df2$LBMC.gent.60. <- as.numeric(ifelse(df2$LBMC.gent.60. == "#DIV/0!", NA, df2$LBMC.gent.60.))

# Calculate log2 ratio
df2$logratio <- log2(df2$LBMC.gent.60. / df2$LBMC)

# Cap positive log ratios at 0 (since mutant should decrease or stay the same)
df2$logratio[df2$logratio > 0] <- 0



# --- Plot : Reference group = Initial Culture ---
p2 <- ggplot(df2, aes(x = Host, y = 2^logratio, color = Host)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, alpha = 0.6) +
  theme_bw() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 2), breaks = c(0, 1, 2)) +
  labs(x = "Plant Genotype",
       y = "Proportion of Malonyl-COA Mutant",
       title = "Malonyl-COA mutant competition outcome") +
  stat_compare_means(label = "p.signif", method = "t.test",
                     ref.group = "Initial Culture", var.equal = FALSE)



print(p2)



dev.off()


```


